fixed search after I broke it by get_request_args now returning None

diff --git a/wrun b/wrun
--- a/wrun
+++ b/wrun
@@ -2,7 +2,12 @@
 
 # hopefully this saves some typing, instead of writing:
 # python scripts/wprefresh.py arg1 arg2
-# I can write: wprun wprefresh arg1 arg2
+# I can write: ./wrun wprefresh arg1 arg2
+#     or just: ./wrun wpstats
+#
+
+
+# script directory to use
 scriptdir="scripts/"
 
 function print_usage () {
@@ -11,16 +16,58 @@ function print_usage () {
     exit 0
     }
 
+function print_fail () {
+	# prints a message and fails with exit code 1
+	printf "$*"
+	exit 1
+	}
+
+function list_script_type () {
+	# list a certain file extension in the scripts dir.
+	# ex: list_script_type ".py"
+	for scriptname in ${scriptdir}*$1
+	do
+		if [ "${scriptname%__init__*}" != "${scriptdir}" ]; then
+			scriptname="${scriptname#$scriptdir*}"
+			printf "    %s\n" "$scriptname"
+		fi
+	done
+}
+
+function list_python_scripts () {
+	printf "\ncurrent python scripts:\n"
+	list_script_type ".py"
+}
+
+function list_bash_scripts () {
+	printf "\ncurrent bash scripts:\n    (..incompatible with ${0})\n"
+	list_script_type ".sh"
+}
+
+function list_scripts () {
+	# list command. shows python and bash scripts in scripts dir.
+	list_python_scripts
+	echo
+	list_bash_scripts
+	echo
+	exit 0
+}
+
+
 # test scriptdir
 if [ ! -d "${scriptdir}" ]; then
-    printf "\nscript dir not found!: %s\n" "${scriptdir}"
-    exit 1
+    print_fail "\nscript dir not found!: ${scriptdir}\n"
 fi
 
 # save original scriptname passed for later
 scriptarg="${1}"
 if  [ -z $scriptarg ] || [ "${scriptarg}" == "-h" ] || [ "${scriptarg}" == "--help" ]; then
     print_usage
+fi
+
+# test for list command
+if [ "${scriptarg}" == "list" ] || [ "${scriptarg}" == "-l" ] || [ "${scriptarg}" == "--list" ]; then
+	list_scripts
 fi
 
 scriptname=$scriptarg
@@ -37,8 +84,7 @@ fi
 
 # TEST filename
 if [ ! -f "${scriptname}" ]; then
-    printf "\ncan't find the script: ${scriptname}\n"
-    exit 1
+    print_fail "\ncan't find the script: ${scriptname}\n"
 fi
 
 # Build argument string (remove previous scriptname)
@@ -53,6 +99,8 @@ do
         fi
     fi
 done
+
+# run with or without args (dont add extra space with no args)
 if [ "${args}" != "" ]; then
     scriptcmd="${scriptname} ${args}"
 else
